/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railwayproject;

import com.google.zxing.WriterException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static railwayproject.excelDB.b1;
import static railwayproject.excelDB.c1;
import static railwayproject.excelDB.j1;
import static railwayproject.excelDB.t1;
import static railwayproject.excelDB.b2;
import static railwayproject.excelDB.j2;
import static railwayproject.excelDB.t2;
import static railwayproject.excelDB.b3;
import static railwayproject.excelDB.j3;
import static railwayproject.excelDB.t3;
import static railwayproject.excelDB.b4;
import static railwayproject.excelDB.j4;
import static railwayproject.excelDB.t4;
import static railwayproject.excelDB.b5;
import static railwayproject.excelDB.j5;
import static railwayproject.excelDB.t5;
import javax.swing.table.DefaultTableModel;
import static railwayproject.QRcodes.encodeTicketDetails;
import static railwayproject.QRcodes.generateQRcode;
//import static railwayproject.QRcodes.path;
import railwayproject.RailwayProject.Journey;
import railwayproject.RailwayProject.Ticket;
import railwayproject.RailwayProject.Train;
import static railwayproject.excelDB.c1;
import static railwayproject.excelDB.g1;
import static railwayproject.excelDB.getCredentialString;
import static railwayproject.excelDB.getLastRowNumber;
import static railwayproject.excelDB.writeDataNumeric;
import static railwayproject.excelDB.writeDataString;

/**
 *
 * @author ASUS
 */
public class UserAccount extends javax.swing.JFrame {
    //we're gonna need it in the method buyticket
    public static Ticket ticket = new Ticket();
    public static Journey journey=new Journey();
    public static Train train = new Train();
    public static int QRindex=0; //to be increased after every generation
    
    /**
     * Creates new form UserAccount
     */
    public UserAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ticketPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        departLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        trainNbrLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        finalPriceLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        QRlabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        KmLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(17, 112, 112));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 84, 84));
        jLabel1.setText("User Account");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Client Status:");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Journeys:");

        nameLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(102, 102, 102));
        nameLabel.setText(c1.getName());

        IDLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        IDLabel.setForeground(new java.awt.Color(102, 102, 102));
        IDLabel.setText(c1.getId()+"");

        addressLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(102, 102, 102));
        addressLabel.setText(c1.address.city);

        statusLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(102, 102, 102));
        statusLabel.setText(c1.clientStatus);

        jTable1.setBackground(new java.awt.Color(47, 51, 111));
        jTable1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {1,j1.date,b1.start,b1.destination,j1.startTime,j1.nbrOfKm,b1.price,t1.services[0]},
                {2,j2.date,b2.start,b2.destination,j2.startTime,j2.nbrOfKm,b2.price,t2.services[0]},
                {3,j3.date,b3.start,b3.destination,j3.startTime,j3.nbrOfKm,b3.price,t3.services[0]},
                {4,j4.date,b4.start,b4.destination,j4.startTime,j4.nbrOfKm,b4.price,t4.services[0]},
                {5,j5.date,b5.start,b5.destination,j5.startTime,j5.nbrOfKm,b5.price,t5.services[0]},
            },
            new String [] {
                "Nbr","Date", "From", "To", "Time", "km", "Price", "Services"
            }
        ));
        //setting the width of columns in jTable
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(20);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(180);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ticketPanel.setBackground(new java.awt.Color(38, 38, 91));
        ticketPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ticket information");

        label.setFont(new java.awt.Font("NSimSun", 1, 16)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("Date:");

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Purchase your ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("NSimSun", 1, 16)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("From:");

        label2.setFont(new java.awt.Font("NSimSun", 1, 16)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("To:");

        label3.setFont(new java.awt.Font("NSimSun", 1, 16)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Train:");

        label4.setFont(new java.awt.Font("NSimSun", 1, 16)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Departure:");

        label5.setFont(new java.awt.Font("NSimSun", 1, 16)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Duration:");

        label6.setFont(new java.awt.Font("NSimSun", 1, 16)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Final Price:");

        dateLabel.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("jLabel12");

        departLabel.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        departLabel.setForeground(new java.awt.Color(255, 255, 255));
        departLabel.setText("jLabel13");

        fromLabel.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        fromLabel.setForeground(new java.awt.Color(255, 255, 255));
        fromLabel.setText("jLabel7");

        toLabel.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        toLabel.setForeground(new java.awt.Color(255, 255, 255));
        toLabel.setText("jLabel8");

        trainNbrLabel.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        trainNbrLabel.setForeground(new java.awt.Color(255, 255, 255));
        trainNbrLabel.setText("jLabel9");

        durationLabel.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        durationLabel.setForeground(new java.awt.Color(255, 255, 255));
        durationLabel.setText("jLabel10");

        finalPriceLabel.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        finalPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        finalPriceLabel.setText("jLabel15");

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LE");

        javax.swing.GroupLayout ticketPanelLayout = new javax.swing.GroupLayout(ticketPanel);
        ticketPanel.setLayout(ticketPanelLayout);
        ticketPanelLayout.setHorizontalGroup(
            ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(63, 63, 63))
            .addGroup(ticketPanelLayout.createSequentialGroup()
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ticketPanelLayout.createSequentialGroup()
                                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label4)
                                    .addComponent(label)
                                    .addComponent(label1)
                                    .addComponent(label2)
                                    .addComponent(label3)
                                    .addComponent(label5))
                                .addGap(23, 23, 23)
                                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departLabel)
                                    .addComponent(durationLabel)
                                    .addComponent(trainNbrLabel)
                                    .addComponent(toLabel)
                                    .addComponent(fromLabel)
                                    .addComponent(dateLabel)))
                            .addGroup(ticketPanelLayout.createSequentialGroup()
                                .addComponent(label6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalPriceLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))))
                    .addGroup(ticketPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(QRlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ticketPanelLayout.setVerticalGroup(
            ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(fromLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(toLabel))
                .addGap(18, 18, 18)
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3)
                    .addComponent(trainNbrLabel))
                .addGap(18, 18, 18)
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4)
                    .addComponent(departLabel))
                .addGap(18, 18, 18)
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label5)
                    .addComponent(durationLabel))
                .addGap(18, 18, 18)
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label6)
                    .addComponent(finalPriceLabel)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QRlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("Km acquired:");

        KmLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        KmLabel.setForeground(new java.awt.Color(102, 102, 102));
        KmLabel.setText(c1.totalKmTravelled+"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel14)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(statusLabel)
                                    .addComponent(KmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(ticketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameLabel))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IDLabel))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(addressLabel))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(KmLabel))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(statusLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(ticketPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i=0; 
        try {
            for(;i<getLastRowNumber("Clients")+1;i++){
                try {
                    if(getCredentialString("Clients",i,2).equals(c1.getName()))
                        break;
                } catch (IOException ex) {
                    Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            // TODO add your handling code here:
            if(getCredentialString("Clients",i,6).equals("regular")){
                c1.buyTicket(ticket);
                String path = "D:/QR codes/qrcode"+QRindex+".png";
                generateQRcode(encodeTicketDetails(ticket,train,journey),100,100,path);
                //QRindex++;
                ImageIcon image = new ImageIcon(path);
                QRlabel.setIcon(image);
                QRlabel.setVisible(true);
                System.out.println(c1.totalKmTravelled);
                KmLabel.setText(c1.totalKmTravelled+"");
                writeDataNumeric("Clients",i,7,c1.totalKmTravelled);
                
            }
            else if(getCredentialString("Clients",i,6).equals("golden")){
                g1.buyTicket(ticket);
                String path = "D:/QR codes/qrcode"+QRindex+".png";
                generateQRcode(encodeTicketDetails(ticket,train,journey),100,100,path);
               // QRindex++;
                ImageIcon image = new ImageIcon(path);
                QRlabel.setIcon(image);
                QRlabel.setVisible(true);
                KmLabel.setText(g1.totalKmTravelled+"");
                writeDataNumeric("Clients",i,7,g1.totalKmTravelled);
            }
            if(c1.totalKmTravelled>10000||c1.numberOfTravels==50&&c1.clientStatus=="regular"){
                 c1.clientStatus="golden";
                 statusLabel.setText(c1.clientStatus);
                 g1=new RailwayProject.GoldenClients(c1.getAge(),c1.getId(),c1.getName(),c1.getAddress(),c1.getPensioner(),c1.numberOfTravels,c1.totalKmTravelled);
                 g1.birthDate=JOptionPane.showInputDialog("Congratulations you've been upgraded to Golden client\nPlease enter your birthday");
                 g1.prefStation=JOptionPane.showInputDialog("please enter your preferred station:");
                
                 //editing the data in the dataBase
                 writeDataString("Clients",i,6,"golden");
                 writeDataString("Clients",i,8,g1.birthDate);
                 writeDataString("Clients",i,9,g1.prefStation);
                 
            }
        } catch (IOException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriterException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        QRlabel.setVisible(false);
        //getting the client status
        int i=0; 
        for(;i<9;i++){
            try {
                if(getCredentialString("Clients",i,2).equals(c1.getName()))
                    break;
            } catch (IOException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        try {
            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            
            //get journey number that was clickek from the table
            int jourNbr = (int) tblModel.getValueAt(jTable1.getSelectedRow(), 0);
            switch(jourNbr){
                case 1:
                    ticket=b1;
                    journey=j1;
                    train=t1;
                    j1.duration=getCredentialString("Journeys",1,3);
                    durationLabel.setText(j1.duration);
                    trainNbrLabel.setText(t1.number+"");
                    dateLabel.setText(j1.date);
                    fromLabel.setText(b1.start);
                    toLabel.setText(b1.destination);
                    departLabel.setText(j1.startTime);
                    
                    //calculating the final price
                //try {
                    // TODO add your handling code here:
                    if(/*getCredentialString("Clients",i,6).equals("regular")*/c1.clientStatus.equals("regular")){
                        c1.calculateFinalPrice(b1);
                    }
                    else if(/*getCredentialString("Clients",i,6)*/c1.clientStatus.equals("golden")){
                        g1.journey=j1;  
                        g1.calculateFinalPrice(b1);
                    }
                /*}catch (IOException ex) {
                    Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
                }*/
                    finalPriceLabel.setText(b1.FinalPrice+"");
                    break;
                case 2:
                    ticket=b2;
                    journey=j2;
                    train=t2;
                    j2.duration=getCredentialString("Journeys",2,3);
                    durationLabel.setText(j2.duration);
                    trainNbrLabel.setText(t2.number+"");
                    dateLabel.setText(j2.date);
                    fromLabel.setText(b2.start);
                    toLabel.setText(b2.destination);
                    departLabel.setText(j2.startTime);
                    
                    //calculating the final price
            
                    // TODO add your handling code here:
                    if(c1.clientStatus.equals("regular")){
                        c1.calculateFinalPrice(b2);
                    }
                    else if(c1.clientStatus.equals("golden")){
                        g1.journey=j2;    
                        g1.calculateFinalPrice(b2);
                    }
                
                    finalPriceLabel.setText(b2.FinalPrice+"");
                    break;
                 case 3:
                    ticket=b3;
                    journey=j3;
                    train=t3;
                    j3.duration=getCredentialString("Journeys",3,3);
                    durationLabel.setText(j3.duration);
                    trainNbrLabel.setText(t3.number+"");
                    dateLabel.setText(j3.date);
                    fromLabel.setText(b3.start);
                    toLabel.setText(b3.destination);
                    departLabel.setText(j3.startTime);
                    
                    //calculating the final price

                    // TODO add your handling code here:
                    if(c1.clientStatus.equals("regular")){
                        c1.calculateFinalPrice(b3);
                    }
                    else if(c1.clientStatus.equals("golden")){
                        g1.journey=j3;    
                        g1.calculateFinalPrice(b3);
                    }
                    finalPriceLabel.setText(b3.FinalPrice+"");
                    break;
                case 4:
                    ticket=b4;
                    journey=j4;
                    train=t4;
                    j4.duration=getCredentialString("Journeys",4,3);
                    durationLabel.setText(j4.duration);
                    trainNbrLabel.setText(t4.number+"");
                    dateLabel.setText(j4.date);
                    fromLabel.setText(b4.start);
                    toLabel.setText(b4.destination);
                    departLabel.setText(j4.startTime);
                    
                    //calculating the final price

                    if(c1.clientStatus.equals("regular")){
                        c1.calculateFinalPrice(b4);
                    }
                    else if(c1.clientStatus.equals("golden")){
                        g1.journey=j4;    
                        g1.calculateFinalPrice(b4);
                    }
                
                    finalPriceLabel.setText(b4.FinalPrice+"");
                    break;
                case 5:
                    ticket=b5;
                    journey=j5;
                    train=t5;
                    j5.duration=getCredentialString("Journeys",5,3);
                    durationLabel.setText(j5.duration);
                    trainNbrLabel.setText(t5.number+"");
                    dateLabel.setText(j5.date);
                    fromLabel.setText(b5.start);
                    toLabel.setText(b5.destination);
                    departLabel.setText(j5.startTime);
                    
                    //calculating the final price
                    if(c1.clientStatus.equals("regular")){
                        c1.calculateFinalPrice(b5);
                    }
                    else if(c1.clientStatus.equals("golden")){
                        g1.journey=j5;    
                        g1.calculateFinalPrice(b5);
                    }
                    finalPriceLabel.setText(b5.FinalPrice+"");
                    break;
                    
            }
            ticketPanel.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new UserAccount().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel KmLabel;
    public static javax.swing.JLabel QRlabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel departLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel finalPriceLabel;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel statusLabel;
    public static javax.swing.JPanel ticketPanel;
    private javax.swing.JLabel toLabel;
    private javax.swing.JLabel trainNbrLabel;
    // End of variables declaration//GEN-END:variables

   
}
